import { pool } from '@/lib/db';
import Link from 'next/link';
import { Bot, Rocket } from 'lucide-react';

export const dynamic = 'force-dynamic';

async function getDeployedFeatures() {
    try {
        // Get features that are deployed
        const res = await pool.query("SELECT * FROM feature_roadmap WHERE status = 'DEPLOYED' ORDER BY created_at DESC");
        return res.rows;
    } catch (err) {
        return [];
    }
}

function toSlug(name: string) {
    return name.replace(/[^a-zA-Z0-9]/g, '').toLowerCase().substring(0, 50);
}

export default async function AILabPage() {
    const features = await getDeployedFeatures();

    return (
        <div className="p-8 min-h-screen bg-black text-white">
            <header className="mb-12">
                <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-400 to-pink-600 text-transparent bg-clip-text">
                    Autonomous Feature Lab
                </h1>
                <p className="text-gray-400 mt-2">
                    These features were researched, designed, and coded entirely by AI Agents.
                </p>
            </header>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {features.map((feature: any) => {
                    const slug = toSlug(feature.feature_name);
                    return (
                        <Link
                            key={feature.id}
                            href={`/app/ai-lab/${slug}`}
                            className="block group"
                        >
                            <div className="bg-gray-900 border border-gray-800 rounded-xl p-6 hover:border-purple-500 transition-all hover:shadow-[0_0_30px_rgba(168,85,247,0.2)]">
                                <div className="flex justify-between items-start mb-4">
                                    <div className="bg-purple-900/30 p-3 rounded-lg text-purple-400 group-hover:bg-purple-600 group-hover:text-white transition-colors">
                                        <Bot size={24} />
                                    </div>
                                    <span className="text-xs font-mono text-gray-500">{feature.created_at ? new Date(feature.created_at).toLocaleDateString() : 'Just now'}</span>
                                </div>
                                <h3 className="text-xl font-bold mb-2 group-hover:text-purple-300">{feature.feature_name}</h3>
                                <p className="text-gray-400 text-sm line-clamp-2">
                                    Generated by Refactor Engine v1.0.
                                    Source: {feature.source}
                                </p>
                                <div className="mt-4 flex items-center text-sm text-purple-500 font-bold opacity-0 group-hover:opacity-100 transition-opacity">
                                    Launch Feature →
                                </div>
                            </div>
                        </Link>
                    );
                })}
            </div>

            {features.length === 0 && (
                <div className="text-center py-20 bg-gray-900/50 rounded-xl border border-dashed border-gray-800">
                    <Bot size={48} className="mx-auto text-gray-700 mb-4" />
                    <h3 className="text-xl font-bold text-gray-500">No Features Deployed Yet</h3>
                    <p className="text-gray-600">The agents are currently building components...</p>
                </div>
            )}
        </div>
    );
}
